const STAGES = [
  ["Input", "resources committed"],
  ["Output", "what was produced"],
  ["Outcome", "what changed for people"]
];

const FN = [
  {
    entry: "Union List · Entry 63",
    title: "Institutions of National Importance",
    note: "Central universities, IITs, NITs and other institutions declared of national importance by Parliament. Bihar hosts IIT Patna, NIT Patna, Central University of South Bihar (Gaya) and Mahatma Gandhi Central University (Motihari).",
    critical: "<strong>Indirect factors:</strong> political interference in appointments; autonomy vs UGC/MoE control; feeder-pipeline (school) quality; faculty brain-drain; weak endowment culture. <strong>Structural finding:</strong> the largest distortion sits at the Input stage — a quarter of sanctioned posts are authorisations, not resources.",
    metrics: [
      { s: 0, name: "Sanctioned teaching posts, central universities", v: "18,951", y: "as on 1 Jul 2025", src: "Ministry of Education, reply in Rajya Sabha (Monsoon Session 2025)", lag: "Session-wise (2–3 replies/yr)", gran: "Institution-level", den: "Absolute posts (56 central universities)", url: "https://sansad.in/rs/questions", st: "audit", why: "The authorised Input. Compare with the vacancy metric — sanction ≠ resource." },
      { s: 0, name: "Faculty vacancy rate, central universities", v: "25.44%", y: "2025 (4,889 of 18,951 posts vacant)", src: "Ministry of Education, Rajya Sabha reply, Winter Session 2025", lag: "Session-wise", gran: "Institution-level", den: "% of sanctioned teaching posts", url: "https://news.careers360.com/central-university-teachers-30pc-women-posts-vacancies-sc-st-obc-faculty-recruitment-jobs-education-ministry-parliament", st: "audit", why: "The Input-stage distortion budgeting can't see: money for posts that hold no person." },
      { s: 0, name: "Reserved-category (SC/ST/OBC) posts vacant", v: "42%", y: "Aug 2023 (3,007 of 7,033 posts)", src: "Ministry of Education, Rajya Sabha reply (via PTI)", lag: "Session-wise", gran: "Category × institution", den: "% of sanctioned reserved posts", url: "https://news.careers360.com/over-42-percent-teaching-posts-for-obc-sc-st-candidates-in-central-universities-vacant-government", st: "audit", why: "Equity disaggregation of the Input — vacancy is not caste-neutral." },
      { s: 1, name: "Total higher-education enrolment (India)", v: "4.50 crore", y: "AISHE 2023-24 (4.33 cr in 2021-22)", src: "All India Survey on Higher Education (AISHE), Ministry of Education", lag: "Annual, ~18-month lag", gran: "Institution / state; Bihar among top-7 enrolment states", den: "Absolute; GER uses 18–23 population", url: "https://aishe.gov.in", st: "self", why: "Self-reported by institutions — treat as Output of capacity use, not learning." },
      { s: 1, name: "Gross Enrolment Ratio, higher education, Bihar", v: "17.1", y: "AISHE 2021-22 (India: 28.4)", src: "AISHE, Ministry of Education; reported in Times of India, Patna", lag: "Annual, ~18-month lag", gran: "State", den: "Per 100 population aged 18–23", url: "https://aishe.gov.in", st: "self", why: "Bihar sits 11.3 points below the national GER — the feeder-pipeline constraint made visible." },
      { s: 2, name: "Unemployment rate among graduates (15+)", v: "13.4%", y: "PLFS 2022-23 (13% in CY 2024)", src: "Periodic Labour Force Survey, NSO/MoSPI", lag: "Annual, ~3-month lag; quarterly for urban", gran: "State × education level", den: "% of graduate labour force", url: "https://www.mospi.gov.in/sites/default/files/press_release/Press_note_AR_PLFS_2023_24_22092024.pdf", st: "survey", why: "INDEPENDENT outcome: a household survey, not a university portal. High graduate unemployment is the employability outcome the Input chain is supposed to buy." },
      { s: 0, name: "Per-student public expenditure", v: "₹10,582", y: "BE 2024-25 ÷ AISHE 2023-24 enrolment", src: "Computed: DoHE allocation ₹47,620 cr (PRS / Union Budget) ÷ 4.50 cr enrolled (AISHE 2023-24)", lag: "Annual (both components)", gran: "National average; institution-level not published as a single series", den: "₹ per enrolled student per year", url: "https://prsindia.org/budgets/parliament/demand-for-grants-2024-25-analysis-education", st: "self", why: "Normalises the Input — raw budgets hide whether spending per student is rising or falling." },
      { s: 0, name: "Competitive research grants received", v: "No data available", y: "—", src: "ANRF / SERB and DST reports do not publish a clean Bihar-INI or per-faculty rupee series", lag: "—", gran: "—", den: "—", url: "https://serb.gov.in", st: "gap", why: "Input quality signal exists in principle (competed grants vs block budget) but no usable public number for these institutions." },
      { s: 1, name: "PhDs awarded per year", v: "32,588", y: "AISHE 2021-22 (India; 18,464 M / 14,124 F)", src: "AISHE, Ministry of Education", lag: "Annual, ~18-month lag", gran: "National; Bihar awarded-count not separately published", den: "Absolute awards (Bihar PhD enrolment was 5,574)", url: "https://aishe.gov.in", st: "self", why: "Research-training Output distinct from enrolment throughput. Bihar-only awards are not in the public AISHE summary." },
      { s: 1, name: "Publications & citations per faculty", v: "No data available", y: "—", src: "SCImago ranks institutions but does not publish a ready per-faculty series for Bihar INIs", lag: "—", gran: "—", den: "—", url: "https://www.scimagoir.com", st: "gap", why: "Independent bibliometric check is possible in principle; a clean papers-per-faculty number for Bihar hosts is not published." },
      { s: 1, name: "Patents filed by academic institutions", v: "No data available", y: "—", src: "IPO Annual Report does not map filings cleanly to Bihar INIs", lag: "—", gran: "—", den: "—", url: "https://ipindia.gov.in", st: "gap", why: "Commercialisation Output — the step between papers and economic outcome — has no usable institutional series here." },
      { s: 2, name: "Median graduate salary (IIT Patna)", v: "₹22.5 LPA", y: "NIRF 2025 cycle (UG 4-year, 2023-24; PG ₹28 LPA)", src: "IIT Patna NIRF 2025 placement disclosure (320 of 335 UG placed)", lag: "Annual", gran: "Institution-level (one Bihar INI)", den: "₹ median annual salary of placed graduates", url: "https://www.nirfindia.org", st: "self", why: "Treat NIRF as noisy self-report. This is the only Bihar INI with a published median; it is not a state graduate-wage figure." },
      { s: 2, name: "Graduate emigration (brain drain)", v: "No data available", y: "—", src: "No official Indian series; only OECD migrant-stock estimates as rough proxy", lag: "—", gran: "—", den: "—", url: "https://www.oecd.org/en/data.html", st: "gap", why: "MEASUREMENT GAP: the most-cited outcome failure of INIs has no denominator — India does not track where its graduates go." },
      { s: 2, name: "National R&D intensity (GERD/GDP)", v: "0.64%", y: "2020-21, DST R&D Statistics", src: "DST, Research & Development Statistics", lag: "Biennial-to-episodic, multi-year lag", gran: "National; sector split", den: "Gross expenditure on R&D as % of GDP", url: "https://dst.gov.in", st: "self", why: "System-level outcome the INI network feeds; roughly a third of the world average." }
    ]
  },
  {
    entry: "Union List · Entry 6",
    title: "Atomic Energy & Mineral Resources",
    note: "Exclusively central: DAE, NPCIL, AERB, uranium exploration. No plant in Bihar — outcomes are measured at the national grid the state draws from.",
    critical: "<strong>Indirect factors:</strong> uranium import dependency and NSG restrictions; Civil Liability for Nuclear Damage Act 2010 deterring suppliers; social license (Kudankulam-type protest); falling solar LCOE eroding the relative case; AERB's independence questioned by CAG.",
    metrics: [
      { s: 0, name: "DAE budget allocation", v: "₹24,969 cr", y: "BE 2024-25 (₹10,447 cr in 2014-15)", src: "Union Budget, Demand for Grants — Department of Atomic Energy", lag: "Annual (Feb), revised estimates mid-year", gran: "Scheme-level within DAE", den: "Absolute ₹; growth rate vs base year", url: "https://www.indiabudget.gov.in", st: "self", why: "The Input. Pair with utilisation from DAE Annual Report — allocation ≠ spend." },
      { s: 1, name: "Installed nuclear capacity", v: "8,880 MW", y: "2025 (25 reactors, 7 stations)", src: "NPCIL / Central Electricity Authority", lag: "CEA monthly; NPCIL annual report", gran: "Reactor-level", den: "MW; % of total installed capacity (~2.3%)", url: "https://www.npcil.nic.in", st: "self", why: "Output, not outcome — capacity installed is not electricity delivered." },
      { s: 1, name: "Nuclear generation", v: "56,681 MU", y: "FY 2024-25 (47,971 MU in FY 2023-24)", src: "NPCIL / PIB factsheet", lag: "Monthly generation reports, ~1-month lag", gran: "Station-level", den: "Million units; PLF % of capacity", url: "https://www.pib.gov.in/FactsheetDetails.aspx?id=149232", st: "self", why: "The corrected Output: generation (GWh) and PLF, not just MW nameplate." },
      { s: 1, name: "Capacity under construction", v: "~6.6 GW", y: "Apr 2025", src: "CEA / PIB (Ministry of Power)", lag: "Annual review; PIB releases", gran: "Project-level", den: "MW; % of 22,480 MW target for 2031-32", url: "https://www.pib.gov.in", st: "self", why: "The pipeline between budget and grid — capacity sanctioned but not yet generating." },
      { s: 2, name: "Share of nuclear in electricity generation", v: "~3%", y: "FY 2024-25", src: "CEA generation statistics", lag: "Annual, ~3-month lag", gran: "National (all-India grid)", den: "% of total TWh generated", url: "https://cea.nic.in", st: "self", why: "The energy-mix outcome against the 100 GW-by-2047 target." },
      { s: 2, name: "Regulatory independence of AERB", v: "Not independent of DAE", y: "CAG Report No. 9 of 2012 (standing finding)", src: "CAG Performance Audit — Activities of Atomic Energy Regulatory Board", lag: "Episodic (one-off performance audit)", gran: "Institutional", den: "Qualitative audit finding", url: "https://cag.gov.in", st: "audit", why: "INDEPENDENT outcome check: CAG found AERB lacks statutory independence from DAE — the regulator is subordinate to the regulated." },
      { s: 0, name: "Scientific & technical staff, DAE", v: "No data available", y: "—", src: "DAE Annual Report does not publish a single public headcount for the latest year", lag: "—", gran: "—", den: "—", url: "https://dae.gov.in", st: "gap", why: "Human-capital Input parallel to the faculty-vacancy metric in UL-63 — sanctioned vs in-position is not on a public dashboard." },
      { s: 0, name: "Domestic uranium production", v: "No data available", y: "—", src: "UCIL / DAE mark production as strategic; only 'highest-ever' qualitative claims are public", lag: "—", gran: "—", den: "—", url: "https://www.ucil.gov.in", st: "gap", why: "The import-dependency Input constraint is real; the tonne figure is not disclosed." },
      { s: 1, name: "Plant Load Factor (fleet)", v: "87%", y: "FY 2024-25 (85% in FY 2023-24)", src: "NPCIL / PIB — average commercial capacity utilisation", lag: "Annual", gran: "Fleet / reactor-level in CEA monthly", den: "% of installed capacity actually generating", url: "https://www.pib.gov.in/FactsheetDetails.aspx?id=149232", st: "self", why: "The efficiency Output that separates nameplate MW from delivered power." },
      { s: 1, name: "Cost & time overruns, nuclear projects", v: "No data available", y: "—", src: "MoSPI Flash Report lists projects but no clean nuclear-only Bihar-relevant aggregate is published", lag: "—", gran: "—", den: "—", url: "https://www.mospi.gov.in", st: "gap", why: "Construction delay is known qualitatively; a single % overrun for the nuclear portfolio is not extracted here." },
      { s: 1, name: "Medical radioisotopes supplied", v: "40 gamma facilities", y: "2025 (6 commissioned in the latest period; 17 MoUs signed)", src: "DAE / BRIT year-end review (PIB)", lag: "Annual", gran: "National facility count, not curies/doses", den: "Operating gamma-processing facilities", url: "https://britatom.gov.in", st: "self", why: "The invisible public benefit of this entry: cancer diagnostics and therapy, not just electricity. Dose-level supply is not published as one number." },
      { s: 2, name: "Nuclear tariff vs solar auction tariff", v: "₹3.9 vs ~₹2.5 / kWh", y: "NPCIL avg FY 2024-25 vs SECI solar auctions 2024-26", src: "NPCIL average tariff (company filings / PL research); SECI reverse-auction discovery around ₹2.5/kWh", lag: "Order-based / per auction", gran: "Station / auction-level", den: "₹ per kWh", url: "https://cercind.gov.in", st: "self", why: "The relative-economics outcome — falling solar prices are the strongest indirect confounder for this entry." },
      { s: 2, name: "Radiation safety events reported", v: "No data available", y: "—", src: "AERB Annual Report INES tables are not summarised as a single public count for the latest year", lag: "—", gran: "—", den: "—", url: "https://aerb.gov.in", st: "gap", why: "Safety outcome — but the latest event-per-reactor-year figure is not on a public dashboard." },
      { s: 2, name: "Public trust in nuclear power", v: "No data available", y: "—", src: "No recurring Indian survey measures nuclear acceptance", lag: "—", gran: "—", den: "—", url: "https://www.mospi.gov.in", st: "gap", why: "MEASUREMENT GAP: social license decides siting (Kudankulam), yet the state runs no opinion series on it." }
    ]
  },
  {
    entry: "Union List · Entry 31",
    title: "Posts, Telephones & Broadcasting",
    note: "Central subject delivered through the Bihar Licensed Service Area (TRAI reporting note: Bihar LSA includes Jharkhand). This is the function where Bihar's numbers are the national floor.",
    critical: "<strong>Indirect factors:</strong> AGR-dues litigation weakening telco balance sheets; state-level right-of-way delays (a state subject bleeding into a Union one); rural electrification gaps for towers; the Jio price shock as a private lever overriding public policy; USOF/DBN corpus historically under-disbursed.",
    metrics: [
      { s: 1, name: "Rural tele-density, Bihar LSA", v: "44.16", y: "Quarter ending Dec 2024", src: "TRAI, Quarterly Performance Indicators Report (pub. 24 Apr 2025)", lag: "Quarterly, ~4-month lag", gran: "Licensed Service Area (Bihar incl. Jharkhand) — not district", den: "Subscriptions per 100 rural population", url: "https://www.trai.gov.in/sites/default/files/2025-04/QPIR-Dec-24%2024_04.pdf", st: "self", why: "Lowest rural tele-density in India. Operator-reported — inflated by inactive SIMs, so treat as upper bound." },
      { s: 1, name: "Internet subscribers, India", v: "1,002.85 mn", y: "Jun 2025", src: "TRAI QPIR (Apr–Jun 2025)", lag: "Quarterly, ~3-month lag", gran: "LSA", den: "Absolute; per 100 population", url: "https://www.trai.gov.in", st: "self", why: "National Output benchmark against which the Bihar LSA gap is read." },
      { s: 2, name: "Women (15–49) who have ever used the internet, Bihar", v: "20.6% → 58.4%", y: "NFHS-5 (2019-21) → NFHS-6", src: "National Family Health Survey, IIPS/MoHFW", lag: "~5-year cycle, ~1-year processing lag", gran: "District-level (finest available for this indicator)", den: "% of surveyed women aged 15–49", url: "http://rchiips.org/nfhs", st: "survey", why: "INDEPENDENT outcome: household survey, not operator data. Lowest in India at NFHS-5; the NFHS-5→6 jump is the cleanest before/after series in this dashboard." },
      { s: 2, name: "Gender gap in digital access, Bihar", v: "2.1×", y: "NFHS-5 (men 43.6% / women 20.6%)", src: "NFHS-5 state fact sheet, Bihar", lag: "~5-year cycle", gran: "State; urban/rural split", den: "Ratio of male to female 'ever used internet' %", url: "http://rchiips.org/nfhs", st: "survey", why: "Equity disaggregation of the outcome — tele-density averages hide who is connected. 43.6 ÷ 20.6 = 2.12." },
      { s: 0, name: "BharatNet GPs service-ready, Bihar", v: "8,340 GPs", y: "as on 31 Dec 2025 (8,053 official GPs)", src: "DoT / USOF annexure to Rajya Sabha Unstarred Q. 1449 (12 Feb 2026)", lag: "Parliamentary reply", gran: "State GP count (BharatNet inventory vs official 8,053 GPs)", den: "GPs connected; ≈100% of official GP stock", url: "https://usof.gov.in/upload/parliament_questions/RSPQ_1449/Annexure_to_RSPQ_1449.pdf", st: "audit", liveId: "bharatnet_bihar", why: "The rural-fibre Input. 8,340 connected vs 8,053 official GPs — inventory definitions differ slightly, so this is effectively full coverage on the official stock." },
      { s: 0, name: "Mobile towers per lakh population, Bihar", v: "No data available", y: "—", src: "DoT parliamentary replies exist episodically but no usable latest state BTS-per-lakh figure was published in a clean table", lag: "—", gran: "—", den: "—", url: "https://sansad.in", st: "gap", why: "Physical-infrastructure Input; without a current BTS count the per-lakh ratio cannot be computed." },
      { s: 1, name: "Average mobile broadband speed, Bihar LSA", v: "Jio 199 · Airtel 106 Mbps", y: "TRAI Independent Drive Test, Nov 2025", src: "TRAI IDT Bihar LSA (PR 01/2026, 2 Jan 2026); Vi 32.09 Mbps, BSNL 4.04 Mbps", lag: "Campaign-based IDT", gran: "LSA routes (city / highway / railway)", den: "Mbps average download, auto-selection mode", url: "https://www.trai.gov.in/sites/default/files/2026-01/PR_No.01of2026.pdf", st: "audit", why: "Quality Output independent of operator claims — connections ≠ usable connectivity." },
      { s: 1, name: "Call drop rate, Bihar LSA", v: "0.27–8.73%", y: "TRAI IDT Nov 2025 (Airtel 0.27 · Jio 0.79 · BSNL 6.79 · Vi 8.73)", src: "TRAI Independent Drive Test, Bihar LSA", lag: "Campaign-based IDT", gran: "LSA × operator", den: "% calls dropped (benchmark ≤2%)", url: "https://www.trai.gov.in/sites/default/files/2026-01/PR_No.01of2026.pdf", st: "audit", why: "Service-quality Output for the voice network the poorest users still depend on. BSNL and Vi miss the 2% benchmark." },
      { s: 1, name: "Post offices, Bihar", v: "9,367 · 7.5 / lakh", y: "as on 31 Mar 2026 (33 HO + 1,045 SO + 8,289 BO)", src: "Department of Posts, Lok Sabha reply; per-lakh computed on ~12.5 cr population", lag: "Parliamentary reply", gran: "Postal circle (Bihar)", den: "Post offices per 1,00,000 population", url: "https://sansad.in/getFile/lsapps/loksabhaquestions/annex/188/AU1766_ZG3eIT.pdf", st: "audit", why: "The posts half of Entry 31. IPPB account stock for Bihar is not in a free public table." },
      { s: 2, name: "UPI transactions per capita, Bihar", v: "44 / person / year", y: "FY 2024-25 (India ~133; Telangana leads)", src: "NPCI state statistics, compiled by Factly", lag: "Annual state compilation", gran: "State", den: "Transactions per person per year", url: "https://factly.in/here-is-how-upi-usage-differs-across-indian-states/", st: "self", why: "Digital-economy outcome riding on connectivity. Bihar is among the lowest per-capita users." },
      { s: 2, name: "eSanjeevani teleconsultations, Bihar", v: "~30,000 / day", y: "May 2025 (40 hubs, 1,238 doctors)", src: "Bihar Health Department performance note (reported, Bihar Say)", lag: "Administrative / press", gran: "State; district targets for some months", den: "Daily consultations (not a published cumulative for 2025)", url: "https://esanjeevani.mohfw.gov.in", st: "self", liveId: "esanjeevani_bihar", why: "Second-order outcome: connectivity converting into healthcare access. National FY 2024-25 volume was 11 cr." },
      { s: 2, name: "DBT transfer volume, Bihar", v: "₹11,517 cr", y: "FY 2024-25 (state portal; 40 of 135 schemes reported)", src: "dbt.bihar.gov.in — Total DBT for FY 2024-25", lag: "Near real-time on portal", gran: "State × scheme", den: "₹ transferred (state-reported; national dbtbharat.gov.in may differ)", url: "http://dbt.bihar.gov.in/wp/Default.aspx", st: "self", liveId: "dbt_bihar", why: "Welfare-delivery outcome that rides entirely on this entry's infrastructure. Only 40 of 135 registered schemes had reported when this figure was read." },
      { s: 2, name: "Internet shutdowns per year, Bihar", v: "No data available", y: "—", src: "SFLC.in tracker exists but no clean published annual count for Bihar 2024 or 2025 was found", lag: "—", gran: "—", den: "—", url: "https://internetshutdowns.in", st: "gap", why: "The state can also destroy this outcome — an independent tracker exists, but a usable yearly total was not on a public summary page." }
    ]
  },
  {
    entry: "State List · Entry 60",
    title: "Taxes on Professions, Trades & Employments",
    note: "Levied in Bihar under the Bihar Professional Tax Act, 2011, administered by the Commercial Taxes Department. Constitutionally capped at ₹2,500/year per person by Article 276(2).",
    critical: "<strong>Indirect factors:</strong> the ₹2,500 ceiling unrevised since 1988 (political inertia at the Union level binding a state tax); Bihar's large informal economy outside the net; interstate migration confusing jurisdiction; GST reshaping the state's overall tax effort. <strong>Natural comparison:</strong> UP, Rajasthan, Haryana and Delhi levy no professional tax at all — inter-state variation is the identification strategy.",
    metrics: [
      { s: 0, name: "Statutory ceiling per person", v: "₹2,500 / yr", y: "Art. 276(2), last revised 1988", src: "Constitution of India, Article 276(2); Bihar Professional Tax Act 2011", lag: "Static (constitutional amendment required)", gran: "Per taxpayer", den: "₹ per person per year", url: "https://www.indiacode.nic.in", st: "statute", why: "An Input-stage parameter frozen for ~four decades — the tax cannot grow with incomes." },
      { s: 1, name: "Professional tax collected, Bihar", v: "₹226.38 cr", y: "FY 2025-26 (₹195.85 cr in 2024-25)", src: "Commercial Taxes Department, Govt of Bihar — provisional annual collection figures", lag: "Annual, announced ~April (provisional)", gran: "State; circle-wise on department portal", den: "Absolute ₹; % growth y-o-y (+15.6%)", url: "https://state.bihar.gov.in/biharcommercialtax/", st: "self", why: "The Output. Note the department itself flags professional-tax data as the last head to be fully accounted." },
      { s: 2, name: "Share of professional tax in state commercial taxes", v: "0.52%", y: "FY 2025-26 (₹226 cr of ₹43,324 cr)", src: "Computed from Commercial Taxes Dept, Bihar annual figures", lag: "Annual", gran: "State", den: "% of total commercial-tax revenue", url: "https://state.bihar.gov.in/biharcommercialtax/", st: "self", why: "The fiscal-significance outcome: a rounding error in the state's own-source revenue — evidence the frozen ceiling has hollowed the tax." },
      { s: 2, name: "Own-tax shortfall vs budget, Bihar", v: "−2.69%", y: "FY 2023-24 (actual ₹48,361 cr vs BE ₹49,700 cr)", src: "CAG, State Finances Audit Report, Bihar 2023-24, Chapter I", lag: "Annual, ~12–18-month lag", gran: "State own-tax aggregate", den: "% deviation of actual own-tax from budget estimate", url: "https://saiindia.gov.in/uploads/download_audit_report/2025/4-SFAR-2023-24-Chapter-I-English-06881e24e00d182.62124837.pdf", st: "audit", why: "INDEPENDENT outcome check on the department's self-reported collections — the budgeted tax effort was not met." },
      { s: 0, name: "Cost of collection ratio", v: "No data available", y: "—", src: "CAG SFAR Bihar does not publish a professional-tax-only ₹-spent-per-₹100-collected figure in the latest chapter", lag: "—", gran: "—", den: "—", url: "https://cag.gov.in/en/audit-report?defualt_term=Bihar", st: "gap", why: "Input-efficiency check: a ₹226 cr tax with high collection cost may be net-negative — but that ratio is not in the public table." },
      { s: 1, name: "Registered enrollees / employers", v: "No data available", y: "—", src: "Bihar Commercial Taxes portal does not publish a clean public enrollee time-series", lag: "—", gran: "—", den: "—", url: "https://state.bihar.gov.in/biharcommercialtax/", st: "gap", why: "The coverage Output — without an enrollee count the tax base cannot be sized." },
      { s: 1, name: "Compliance gap vs eligible workforce", v: "No data available", y: "—", src: "Cannot compute: department enrollee numerator is unpublished (PLFS salaried denominator exists)", lag: "—", gran: "—", den: "—", url: "https://www.mospi.gov.in", st: "gap", why: "The informality distortion is measurable only if both enrollee count and PLFS salaried workforce are public. The numerator is missing." },
      { s: 2, name: "EPFO net payroll additions, Bihar", v: "No data available", y: "—", src: "EPFO monthly payroll is published nationally; a free public Bihar monthly total was not found", lag: "—", gran: "—", den: "—", url: "https://www.epfindia.gov.in", st: "gap", why: "Formalisation outcome — the base on which any profession tax must grow — is not in an open state table." },
      { s: 2, name: "Own-tax share of revenue receipts, Bihar", v: "25.0%", y: "FY 2023-24 (₹48,361 cr of ₹1,93,347 cr)", src: "Computed from CAG SFAR / Finance Accounts, Bihar 2023-24", lag: "Annual, ~12–18-month lag", gran: "State", den: "Own tax revenue as % of total revenue receipts", url: "https://saiindia.gov.in/uploads/download_audit_report/2025/4-SFAR-2023-24-Chapter-I-English-06881e24e00d182.62124837.pdf", st: "audit", why: "The fiscal-autonomy outcome. Union-tax share was 58.8% of the same receipts — Bihar remains transfer-dependent." }
    ]
  },
  {
    entry: "State List · Entry 44",
    title: "Treasure Trove",
    note: "Governed by the colonial Indian Treasure Trove Act, 1878 — which still defines 'treasure' as anything worth more than ₹10. Administration sits with district collectors; antiquities overlap with ASI (central), creating a jurisdiction seam.",
    critical: "<strong>Indirect factors:</strong> perverse incentive design — a low finder's reward pushes non-reporting, so the true find rate has an unknown denominator (a classic dark-figure problem); ASI-vs-state overlap; international antiquities demand driving smuggling; valuation/custody corruption. This entry is the dashboard's honest data gap: no department publishes a regular Bihar series.",
    metrics: [
      { s: 0, name: "Statutory 'treasure' threshold", v: "₹10", y: "Indian Treasure Trove Act, 1878 (in force)", src: "India Code — Act VI of 1878, Section 3", lag: "Static since 1878", gran: "National statute, state-administered", den: "₹ value of find", url: "https://www.indiacode.nic.in/handle/123456789/2already?view_type=browse", st: "statute", why: "Pair with the ₹2,500 professional-tax ceiling: two unindexed statutory figures, one failure mode." },
      { s: 1, name: "Idol / antique theft cases, Bihar", v: "8 cases", y: "NCRB Crime in India 2024 (11 cases in 2025, state police)", src: "NCRB Crime in India 2024, BNS 305(d); Bihar Police 2025 figures via Times of India", lag: "Annual, ~12–24-month lag", gran: "State", den: "Cases per year (national total 465; Odisha 151)", url: "https://ncrb.gov.in/crime-in-india.html", st: "audit", why: "Inverse proxy for the Output: reported theft is the visible tail of non-reported finds. Bihar ranked 15th of 36 states/UTs." },
      { s: 2, name: "Preservation of monuments & antiquities", v: "Adverse findings", y: "CAG Report No. 18 of 2022", src: "CAG Performance Audit — Preservation and Conservation of Monuments and Antiquities (ASI)", lag: "Episodic performance audit", gran: "Institutional / site-level", den: "Qualitative audit findings", url: "https://cag.gov.in", st: "audit", why: "INDEPENDENT outcome check: CAG documented weak antiquity registration and custody — the heritage-preservation outcome this entry exists to secure." },
      { s: 0, name: "Art, Culture & Youth Dept budget, Bihar", v: "No data available", y: "—", src: "Bihar Budget Demand for Grants for this department is not extracted as a single public headline figure", lag: "—", gran: "—", den: "—", url: "https://state.bihar.gov.in/finance/", st: "gap", why: "The administrative Input behind district-collector treasure administration is not on a public one-line table." },
      { s: 1, name: "Treasure trove finds reported per year, Bihar", v: "No data available", y: "—", src: "No state or central department publishes a series; RTI to district collectors is the only route", lag: "—", gran: "—", den: "—", url: "https://rtionline.gov.in", st: "gap", why: "THE core measurement failure of this entry: the Output the 1878 Act exists to generate is recorded nowhere." },
      { s: 1, name: "Antiquities documented (NMMA)", v: "No data available", y: "—", src: "NMMA does not publish a current Bihar-only documentation total on a public dashboard", lag: "—", gran: "—", den: "—", url: "https://nmma.nic.in", st: "gap", why: "The registration Output that would make theft detectable — CAG found it badly incomplete, and no usable count is public." },
      { s: 2, name: "Antiquities seized (smuggling interdiction)", v: "No data available", y: "—", src: "DRI annual report is national and case-wise; Bihar attribution is not a published total", lag: "—", gran: "—", den: "—", url: "https://dri.nic.in", st: "gap", why: "Independent inverse proxy in principle; no Bihar-attributable seizure total is on a public summary." },
      { s: 2, name: "Artefacts repatriated to India", v: "No data available", y: "—", src: "Ministry of Culture / PIB announce items case-by-case; no official cumulative public stock for the latest year", lag: "—", gran: "—", den: "—", url: "https://www.pib.gov.in", st: "gap", why: "End-of-pipe outcome: what returns after every upstream stage of this chain failed — not published as one official stock." },
      { s: 2, name: "Tourist arrivals, Bihar", v: "821.33 lakh", y: "2023 (815.86 lakh domestic · 5.47 lakh foreign)", src: "Bihar Economic Survey 2024-25, Chapter 14 (Tourism)", lag: "Annual, ~1-year lag", gran: "State (not ASI ticketed-monument split)", den: "Domestic + foreign visitors per year", url: "https://state.bihar.gov.in/finance/", st: "self", why: "The public-benefit outcome of preserved heritage. ASI monument-wise ticketed footfall for Nalanda / Vikramshila is not in the state survey table." }
    ]
  },
  {
    entry: "Twelfth Schedule · Entry 18 (ULB: Patna)",
    title: "Regulation of Slaughterhouses & Tanneries",
    note: "Function of the Patna Municipal Corporation. Bihar's tannery footprint is small; in Patna the function is dominated by meat- and fish-shop licensing and effluent into the Ganga.",
    critical: "<strong>Indirect factors:</strong> effluent-treatment (CETP) capacity; enforcement intensity shifting with local politics; bribery sustaining unlicensed units; livelihood dependence of specific communities (equity dimension); NGT/Supreme Court Ganga orders overriding municipal discretion. <strong>Measurement finding:</strong> most former 'no data' cells were state-level series or extraction failures, not non-existence — AHIDF is ₹0 to Patna at a 1% statewide approval rate; occupational health of slaughterhouse workers remains a true gap.",
    metrics: [
      { s: 1, name: "Meat & fish shops identified in PMC area", v: "1,420", y: "PMC enforcement drive, Apr 2026", src: "Patna Municipal Corporation review meeting (reported, Patna Press)", lag: "Campaign-based / administrative real-time", gran: "Zone-wise within PMC", den: "Absolute count of establishments", url: "https://patnapress.com/patna-municipal-corporation-cctv-garbage-crackdown-april-2026/", st: "self", why: "The universe against which licensing performance is read." },
      { s: 1, name: "Shops licensed or renewed", v: "72 (5.1%)", y: "Apr 2026; 880 declared illegal", src: "Patna Municipal Corporation (reported, Patna Press); 72 ÷ 1,420 = 5.1%", lag: "Campaign-based", gran: "Zone-wise", den: "% of identified establishments", url: "https://patnapress.com/patna-municipal-corporation-cctv-garbage-crackdown-april-2026/", st: "self", why: "The Output-stage collapse in one number: 95% of the trade sits outside the licensing regime this entry assigns to the ULB." },
      { s: 1, name: "QR-coded licensing regime", v: "Introduced", y: "Feb 2026 guideline", src: "PMC licensing guideline (reported, First Bihar)", lag: "One-off policy; compliance data to follow", gran: "Shop-level", den: "Shops issued QR licence / total identified — compliance count not yet published", url: "https://firstbihar.com/bihar/patna-news/patna-meat-fish-shop-license-qr-code-guideline-133605", st: "self", why: "Licensing reform — creates the shop-level administrative series this function previously lacked. Issued-licence count after the guideline is not public yet." },
      { s: 2, name: "Ganga water quality at Patna", v: "Unfit for bathing", y: "BSPCB 2023-24 (34 Bihar sites fail coliform since 2020-21)", src: "Bihar State Pollution Control Board submissions to NGT; BSPCB annual report 2023-24", lag: "Annual board report; NGT filings", gran: "Monitoring-station / ghat level", den: "Bathing standard failed on faecal coliform (BOD station table not extracted)", url: "https://indianexpress.com/article/india/bihar-ganga-water-faecal-coliform-pollution-9892944/", st: "audit", why: "CPCB/BSPCB is independent of the PMC. Patna STPs also run far below design capacity (installed ~350 MLD vs discharge >700 MLD)." },
      { s: 2, name: "NGT monitoring of Ganga pollution (Bihar)", v: "34 sites non-compliant", y: "BSPCB to NGT, 2024–25 (O.A. 673/2018 & related)", src: "National Green Tribunal record; BSPCB affidavit on faecal coliform", lag: "Episodic (order-based)", gran: "State / drain-level", den: "Sites failing bathing-quality criteria", url: "https://greentribunal.gov.in", st: "audit", why: "INDEPENDENT outcome check: judicial monitoring exists precisely because municipal self-reporting failed." },
      { s: 0, name: "ULB enforcement workforce vacancy, Bihar", v: "57% vacant · 96–99% technical", y: "CAG Local Bodies, Sept 2016 (40% vacant in Mar 2007)", src: "CAG Report No. 4 of 2017 — Local Bodies, Government of Bihar, Chapter III. Of 12,453 sanctioned ULB posts, 7,145 vacant (57%). Assistant Engineer 96% vacant; Junior Engineer 99% vacant. Recruitment freeze since 1990. Not PMC-veterinary-specific — it is the independent audit of the functionary Input this municipal function runs on.", lag: "Episodic performance audit", gran: "ULB class (corporation / council / nagar panchayat); designation-wise for technical posts", den: "% of sanctioned posts vacant", url: "https://cag.gov.in/uploads/download_audit_report/2017/Chapter_3_An_Overview_Of_Functioning_Of_The_Urban_Local_Bodies_In_Bihar_of_Report_No.4_of_2017_-_Local_Bodies_Government_of_Bihar.pdf", st: "audit", why: "PMC does not publish a veterinary-inspector headcount. CAG measured the same Input at ULB level: functionaries were grossly inadequate. FSSAI Food Safety Officer recruitment rounds (roughly 91–105 posts statewide) are notifications, not cadre strength." },
      { s: 0, name: "AHIDF projects approved, Bihar / Patna", v: "6 of 572 (1.0%) · Patna ₹0", y: "2020-21 to 22 Jul 2025 (PAC-approved ₹232.16 cr)", src: "Lok Sabha written answer, 29 Jul 2025 (PIB 2149832), DAHD. 572 Bihar projects received (cost ₹2,401.16 cr; term loan ₹259.77 cr); 6 approved — Gopalganj 1 (₹12.13 cr), Kishanganj 1 (₹42.77 cr), Muzaffarpur 3 (₹140.76 cr), Purnia 1 (₹36.50 cr). Interest subvention released ₹13.15 cr. Patna is not in the table.", lag: "Parliamentary reply", gran: "State; district for the 6 approvals", den: "Projects approved / received; ₹ to Patna vs Bihar", url: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2149832", st: "audit", why: "Central-scheme Input into a municipal function. Not a data gap: 1% statewide approval and ₹0 to Patna is the jurisdiction-seam finding." },
      { s: 1, name: "FSSAI licenses & registrations, Bihar", v: "59,087 active", y: "FoSCoS as on 30 Sep 2021 (352 central · 20,909 state · 37,826 registrations)", src: "FSSAI / FoSCoS state-wise issued-expired-active table, 30 Sep 2021. Issued stock was larger (652 CL · 33,550 SL · 74,506 registrations). Parliament Q&As reproduce the same state tables.", lag: "Portal snapshot; FSSAI last posted this extract in 2021", gran: "State (not slaughterhouse-only; not Patna-only)", den: "Active licences + registrations. Compare with PMC's 72 licensed meat/fish shops.", url: "https://www.fssai.gov.in/upload/uploadfiles/files/SNo7_FLRS_FoSCoS_Data_CL_SL_Registration_Issued_Expired_Active_Sept_30_10_2021.pdf", st: "self", why: "The parallel central licensing Output. The table was always published — a flipbook/PDF extract problem, not a missing series. Dual-regime: 59,087 state FBOs vs 72 PMC meat-shop licences." },
      { s: 1, name: "Animals slaughtered / meat production, Bihar", v: "4.21 lakh tonnes", y: "BAHS 2024-25 (404.3 thousand t in 2023-24)", src: "DAHD, Basic Animal Husbandry Statistics — Integrated Sample Survey (state-wise animals slaughtered and meat from recognised/registered vs unregistered slaughterhouses). Bihar Assembly reply: ~150 slaughterhouses operating statewide, of which only a few were legal. No Patna ante/post-mortem series is published.", lag: "Annual BAHS, ~6–12-month lag", gran: "State (ISS); not Patna municipal veterinary records", den: "Thousand tonnes meat; registered vs unregistered split is in BAHS tables", url: "https://www.dahd.gov.in/en/schemes/programmes/animal-husbandry-statistics", st: "survey", why: "Patna inspection counts are unpublished. The Output is recorded at state level: survey-based slaughter and meat, plus an Assembly finding that almost all of ~150 units sit outside the legal regime." },
      { s: 2, name: "Childhood diarrhoea (under-5), Bihar", v: "13.7%", y: "NFHS-5 2019-21 (India 7.3%; NFHS-4 Bihar 10.4%)", src: "NFHS-5 state fact sheet, Bihar (IIPS/MoHFW). Highest among major states. District factsheets (including Patna) carry the same indicator. IDSP/IHIP weekly outbreak reports name Bihar districts but no compiled Patna annual total is published.", lag: "~5-year survey cycle", gran: "State; district on NFHS-5 factsheets", den: "% of children under 5 with diarrhoea in the 2 weeks before survey", url: "https://dhsprogram.com/pubs/pdf/OF43/OF43.BR.pdf", st: "survey", why: "INDEPENDENT outcome, not the municipality's. Outbreak counts measure reporting effort; a household survey of childhood diarrhoea is the cleaner public-health result of unregulated meat and effluent." },
      { s: 2, name: "Export abattoirs & livestock share, Bihar", v: "3 APEDA plants · 0 in Patna", y: "APEDA list 2024–26; 20th Livestock Census 2019", src: "APEDA registered integrated abattoir-cum-processing plants (Al Sameer and Zakariya Agro, Araria/Forbesganj; ABZ Agro Foods, Kishanganj). None in Patna. 20th Livestock Census: Bihar 7.7 mn buffalo of 109.85 mn (7.0%) and 12.82 mn goats of 148.88 mn (8.6%). Port-based export rupees are unreliable; the plant list answers the export-vs-environment question without them.", lag: "APEDA list updated periodically; census decadal", gran: "Plant address; state livestock stock", den: "Count of APEDA-registered plants in Bihar / Patna; % of all-India buffalo and goat", url: "https://apeda.gov.in/List-Abattoirs-meat", st: "audit", why: "The export-vs-environment tension, measured where the plants actually sit. Bihar has the herd; Patna has the unlicensed shops and none of the registered export abattoirs." },
      { s: 2, name: "Occupational health of slaughterhouse workers", v: "No data available", y: "—", src: "No Indian national dataset. DGFASLI covers registered factories only, so most of this workforce is outside its frame. PLFS counts workers by NIC code, not health outcomes. Literature is Nigeria, New Zealand, Malaysia, Bangladesh.", lag: "—", gran: "—", den: "—", url: "https://www.dgfasli.gov.in", st: "gap", why: "True measurement gap with an equity edge: the workforce is drawn from specific marginalised communities, and no Indian agency measures their health burden." }
    ]
  },
  {
    entry: "Eleventh Schedule · Entry 2 (PRI: Bihar)",
    title: "Land Improvement, Land Reforms, Consolidation & Soil Conservation",
    note: "Full entry text matters: 'land improvement, implementation of land reforms, land consolidation and soil conservation.' Consolidation is the live issue in Bihar — the state has India's most fragmented holdings.",
    critical: "<strong>Indirect factors:</strong> land-records status (Bihar Special Survey & Settlement running since 2020 across ~45,000 villages); elite capture at panchayat level; overlap with central schemes (MGNREGA, PM-KISAN); landowner resistance; caste–land correlation; inheritance-driven fragmentation; climate variability. <strong>Real Input for a devolved function is the 3Fs</strong> — funds, functions, functionaries actually devolved (Devolution Index), not scheme allocation on paper.",
    metrics: [
      { s: 2, name: "Average operational holding, Bihar", v: "0.39 ha", y: "Latest published: Agriculture Census 2015-16 (India 1.08 ha). 2021-22 census done, results not released", src: "10th Agriculture Census 2015-16, Dept of Agriculture & Farmers Welfare (agcensus.da.gov.in). 11th Census (reference year 2021-22) launched 28 Jul 2022; MoS Ramnath Thakur told Lok Sabha (Jul 2026) that all three phases of fieldwork are complete, but no All-India or Bihar holding-size tables have been published.", lag: "Quinquennial; 2021-22 still in processing/validation", gran: "District × size-class × social group (when published)", den: "Hectares per operational holding", url: "https://agcensus.da.gov.in", st: "survey", why: "The fragmentation outcome consolidation is meant to reverse. 2015-16 is the latest public number — not because 2022 was skipped, but because DA&FW has not released 2021-22 results yet." },
      { s: 2, name: "Small & marginal share of holdings, Bihar", v: "~97%", y: "Latest published: Agriculture Census 2015-16 (India 86.1%). 2021-22 census done, results not released", src: "10th Agriculture Census 2015-16; SLBC Bihar / Bihar Economic Survey still cite 2015-16. 11th Census 2021-22 fieldwork complete (Lok Sabha, Jul 2026); size-class tables for Bihar not yet on agcensus.da.gov.in.", lag: "Quinquennial; 2021-22 still in processing/validation", gran: "District × size-class", den: "% of operational holdings below 2 ha", url: "https://agcensus.da.gov.in", st: "survey", why: "Marginal holdings averaged 0.25 ha in 2015-16 — below the viability threshold for mechanisation. No 2021-22 size-class split is public yet." },
      { s: 2, name: "Average monthly income, agricultural household (Bihar)", v: "₹7,542", y: "NSS 77th Round, SAS 2018-19 (India: ₹10,218)", src: "NSS 77th Round — Situation Assessment of Agricultural Households, NSO/MoSPI", lag: "Decadal-to-episodic; ~2-year processing lag", gran: "State; by holding size-class", den: "₹ per agricultural household per month", url: "https://www.mospi.gov.in", st: "survey", why: "INDEPENDENT outcome: household survey of farmer income — the result the whole chain is supposed to move." },
      { s: 1, name: "Agriculture & allied share of Bihar GSVA", v: "~20%", y: "FY 2021-22 (Quick Estimates)", src: "Bihar Economic Survey (Finance Dept, GoB); SLBC compilation", lag: "Annual (pre-budget release)", gran: "State; sector-level", den: "% of Gross State Value Added", url: "https://state.bihar.gov.in/finance/", st: "self", why: "Sector-productivity Output against which land-reform effort is judged." },
      { s: 0, name: "State allocation to agriculture & allied", v: "₹7,726 cr", y: "Bihar budget, FY cited in Economic Survey", src: "Bihar Budget / Economic Survey, Finance Department GoB", lag: "Annual (Feb–Mar)", gran: "Department / scheme", den: "Absolute ₹; % of state budget", url: "https://state.bihar.gov.in/finance/", st: "self", why: "The Input — but note the critical box: for a PRI function, devolved untied funds are the truer Input than departmental allocation." },
      { s: 0, name: "Land records digitised, Bihar", v: "100% RoR · 4.35 cr records", y: "DILRMP MIS (45,857 of 45,858 villages CLR)", src: "Digital India Land Records Modernisation Programme dashboard, DoLR", lag: "Near real-time", gran: "District-level, component-wise", den: "% of villages with computerised RoR", url: "https://dilrmp.gov.in", st: "self", liveId: "dilrmp_bihar", why: "The records Input that decides whether any land reform is even implementable. Digitised ≠ mutation-updated (43% of sampled RoRs still carry un-updated inheritance)." },
      { s: 0, name: "Panchayat devolution index, Bihar", v: "48.24", y: "MoPR Devolution Index 2024 (national avg 43.89)", src: "Ministry of Panchayati Raj — Devolution Index (PIB document, Feb 2025)", lag: "Episodic", gran: "State", den: "Composite 3F score (funds, functions, functionaries)", url: "https://static.pib.gov.in/WriteReadData/specificdocs/documents/2025/feb/doc2025213501601.pdf", st: "audit", why: "The truer Input for a devolved function: whether the PRI actually holds this power at all. Bihar is a moderate scorer, above the national average." },
      { s: 1, name: "Online mutations completed, Bihar", v: "No data available", y: "—", src: "Bihar Bhumi mutation dashboard is unarchived; no public annual disposed-vs-filed total", lag: "—", gran: "—", den: "—", url: "https://biharbhumi.bihar.gov.in", st: "gap", why: "Output of the records system — the portal keeps no public archive, so a yearly number cannot be cited." },
      { s: 1, name: "Soil health cards issued, Bihar", v: "1.54 crore", y: "as of Jul 2025 (since scheme inception)", src: "PIB — Soil Health & Fertility / PM-RKVY note on Bihar", lag: "Scheme-cycle reporting", gran: "State cumulative", den: "Cards issued (not cards per 100 holdings in the latest cycle)", url: "https://static.pib.gov.in/WriteReadData/specificdocs/documents/2025/sep/doc2025912633901.pdf", st: "self", liveId: "soil_health_bihar", why: "The soil-conservation half of Entry 2, usually forgotten next to land reform." },
      { s: 1, name: "Watershed area treated, Bihar", v: "No data available", y: "—", src: "WDC-PMKSY MIS does not publish a free public Bihar treated-vs-sanctioned hectare total", lag: "—", gran: "—", den: "—", url: "https://wdcpmksy.dolr.gov.in", st: "gap", why: "Physical conservation Output; sanctioned-vs-treated would expose the utilisation gap if the hectare table were public." },
      { s: 2, name: "Pending cases, Bihar district courts", v: "37.65 lakh", y: "NJDG current snapshot (21% pending >10 years)", src: "National Judicial Data Grid, Bihar state view (civil 5.45 lakh · criminal 32.20 lakh)", lag: "Near real-time", gran: "District-court level; land-case filter not published as a single total", den: "Pending cases (all types). Land/property split is not a public NJDG aggregate.", url: "https://njdg.ecourts.gov.in", st: "audit", liveId: "njdg_bihar", why: "Second-order outcome: bad land records convert into litigation. NJDG does not publish a land-only pending total, so the all-case stock is what is public." },
      { s: 2, name: "Land-conflict incidents, Bihar", v: "No data available", y: "—", src: "Land Conflict Watch maps cases but no official public stock for Bihar was extracted", lag: "—", gran: "—", den: "—", url: "https://www.landconflictwatch.org", st: "gap", why: "Independent conflict outcome no government portal records — and no usable public count was on the summary page." },
      { s: 2, name: "Tenancy incidence, Bihar", v: "17.4% of operated area", y: "NSS 70th (2012-13), Bihar + Jharkhand", src: "NSS Land & Livestock Holdings; Sharma/Rodgers compilation. NSS 77th Bihar-only leased-in % was not in a free extract.", lag: "Episodic (~6–8-year gaps)", gran: "State (here Bihar+JH combined in the published table)", den: "% of operational area leased-in", url: "https://www.mospi.gov.in", st: "survey", why: "Measures the informal tenancy that Bihar's unfinished land reform pushed underground. Village studies put the share higher (up to ~38%)." },
      { s: 2, name: "Out-migration from Bihar", v: "74.54 lakh (7.2%)", y: "Census 2011 (22.65 lakh / 30% moved for work)", src: "Census of India D-tables; Indian Express compilation of inter-state out-migrants", lag: "Decadal", gran: "State", den: "Out-migrants as % of 2011 population; work-reason share", url: "https://indianexpress.com/article/political-pulse/why-migration-jobs-campaigns-key-bihar-poll-players-nda-mahagathbandhan-9967466/", st: "survey", why: "The distress outcome of unviable holdings — the fragmentation metrics' human consequence. No newer Census migration table exists." }
    ]
  }
];

const STAMP_LABELS = {
  survey: "Survey",
  audit: "Audit",
  self: "Self-reported",
  statute: "Statute",
  fill: "Verify",
  gap: "No data"
};

const STAGE_COLORS = ["#14b8a6", "#f59e0b", "#ec4899"];
const STAGE_BADGES = ["IN", "OUT", "OC"];
